import type { HelpArticle } from "./help-articles";

/** Marketplace upload steps checked against the linked official guides on 2026-10-02. */
export const extraHelpArticles: HelpArticle[] = [
  { slug: "pack-failed-or-needs-review", title: "When a pack fails or images need review", group: "Making packs", structured: "always", body: ["Open the pack to see which images passed. An image marked for review did not pass its checks and is not charged. Passed images remain available to download.", "Use Try this shot again where it is offered. Credits are held while it runs and charged only if it passes. If you still need help, use Contact us and include the pack link."] },
  { slug: "download-your-files", title: "Download your files", group: "Making packs", structured: "always", body: ["Open a finished pack and use its download controls to save the files. You can also download an individual image below its preview.", "If an image has versions, pick the version you want before downloading. Upload the downloaded file to your store. A screenshot or a share page preview may have different dimensions and metadata."] },
  { slug: "upload-images-to-amazon", title: "Upload your images to Amazon Seller Central", group: "Selling channels", structured: "always", body: ["Download your Amazon files from the pack. In Seller Central, open Image Manager and find the product by ASIN or SKU. Select the appropriate image variant and upload the matching file.", "Use the white background main image for the main slot and the other listing images for additional slots. Review the result and any warnings in Seller Central. Curvi does not upload or change your listing for you."], sources: [{ label: "Amazon image upload guide", url: "https://sellercentral.amazon.com/help/hub/reference/external/GUGPCYWV2P8KVFUT?locale=en-US" }] },
  { slug: "upload-images-to-shopify", title: "Upload your images to Shopify", group: "Selling channels", structured: "always", body: ["Download your Shopify files. In Shopify admin, open Products and choose your product. In Media, choose Upload new or drag the downloaded files into the section.", "Move the image you want featured to the first position. Review the product page after saving your changes. Curvi does not change your store automatically."], sources: [{ label: "Shopify product media guide", url: "https://help.shopify.com/en/manual/products/product-media/add-media" }] },
  { slug: "upload-to-other-marketplaces", title: "Upload to Etsy, eBay, Walmart and TikTok Shop", group: "Selling channels", structured: "always", body: ["Download the files made for your channel. On Etsy, open Shop Manager, then Listings, and edit the listing to add photos. On eBay, use the listing form's picture section to add the downloaded files.", "For Walmart and TikTok Shop, open the product in your seller account and use its image or media controls. The official guides below explain the current screens for your account. Check the image order and preview before saving. Curvi does not send your files to these marketplaces."], sources: [{ label: "Etsy listing guide", url: "https://help.etsy.com/hc/en-us/articles/115015628707-How-to-Create-a-Listing" }, { label: "eBay pictures guide", url: "https://www.ebay.com/help/selling/listings/adding-pictures-listings?id=4148" }, { label: "Walmart item setup guide", url: "https://marketplacelearn.walmart.com/guides/Item%20setup/Item%20setup/Add-a-New-Item:-Create-a-new-item" }, { label: "TikTok Shop product guide", url: "https://seller-us.tiktok.com/university/essay?knowledge_id=6581713858676522&lang=en" }] },
  { slug: "refunds-and-money-back-promise", title: "Refunds and the money back promise", group: "Billing and account", status: "coming_soon", structured: "never", body: ["A money back promise is coming soon, subject to legal approval. See the current terms for the refund policy, or contact us about a payment."] },
  { slug: "credit-history-and-invoices", title: "Credit history and invoices", group: "Billing and account", structured: "when_purchasable", body: ["Open Billing to see your credit history and invoices. Credit history explains credits added, held, charged or returned for your workspace.", "Invoice and payment controls are available to workspace owners and admins. If you need a payment checked, use Contact us and choose Billing."] },
  { slug: "why-your-pack-is-waiting", title: "Why your pack is waiting", group: "Making packs", structured: "always", body: ["A waiting pack has been accepted and will start when capacity is available. Its page shows its place in your workspace's queue and an estimated wait when available. The estimate can change as other work finishes.", "You can leave the page and return later. If new packs are paused for maintenance, the status page shows the interruption. Starting another copy will not make the first pack finish sooner."] },
  { slug: "make-a-new-version", title: "Make a new version of an image", group: "Making packs", structured: "always", body: ["On an eligible finished lifestyle image, choose Make another version. Review the credit cost and confirm to start. The product stays the same while Curvi makes a new scene around it.", "The existing version stays picked. Review the new version and pick it if you prefer it. This control is unavailable for main images, carousels, images at their version limit, and packs whose source photo has been deleted."] },
  { slug: "delete-your-account-and-data", title: "Delete your account and data", group: "Billing and account", structured: "always", body: ["Open Settings and find Your data to export your data or request account deletion. Read the confirmation carefully before deleting.", "The privacy policy explains which records must remain and how long encrypted backups are kept. Contact us if the deletion page says it needs help to finish."] },
  { slug: "invite-your-team", title: "Invite your team", group: "Billing and account", status: "coming_soon", structured: "never", body: ["Team invitations are coming soon. Contact us if you need more people in your workspace."] },
  { slug: "change-your-email", title: "Change your email", group: "Billing and account", structured: "always", body: ["In Settings, use Change email and enter an address you can keep. Curvi sends a confirmation link to your old address and your new one.", "Open both links and press the confirmation button on each page. Your sign in email changes when both are confirmed. If a link no longer works, return to Settings and start again."] },
];
