import {afterAll,beforeAll,expect,it} from "vitest";
import type {Db} from "@curvi/db";
import {createTestDb} from "@curvi/db/testing";
import {tierByKey,weeklyReport} from "@curvi/pipeline/seed";
import {DbMetricsReader,weeklyMetricLines} from "./weekly-report";
const NOW=new Date("2026-10-05T13:00:00Z");
let test:Awaited<ReturnType<typeof createTestDb>>;
beforeAll(async()=>{test=await createTestDb();});
afterAll(async()=>{await test.client.close();});
it("reads actual billing, jobs, cost and operational fixtures into all three report sections",async()=>{
 const c=test.client,ws="bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",p="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",job="cccccccc-cccc-4ccc-8ccc-cccccccccccc";
 await c.query("insert into workspaces(id,name) values($1,'Weekly')",[ws]);
 await c.query("insert into products(id,workspace_id,title,mode) values($1,$2,'Mug','listing')",[p,ws]);
 await c.query("insert into subscriptions(workspace_id,tier,cadence,status,created_at) values($1,'starter','annual','active','2026-09-01')",[ws]);
 await c.query("insert into generation_jobs(id,workspace_id,product_id,status,created_at,started_at,finished_at,credits_charged,cogs_micros) values($1,$2,$3,'done','2026-10-03T12:00Z','2026-10-03T12:11Z','2026-10-03T12:15Z',10,100000)",[job,ws,p]);
 await c.query("insert into assets(workspace_id,job_id,shot_type,approved) values($1,$2,'main',true),($1,$2,'scene',false)",[ws,job]);
 await c.query("insert into events(workspace_id,name,props,at) values($1,'funnel.payment','{\"kind\":\"topup\",\"amount_usd\":12.5}','2026-10-03'),($1,'funnel.first_payment','{}','2026-10-03')",[ws]);
 await c.query("insert into spend_cap_counters(key,total_micros) values('caps:global:2026-10-05',2500000),('llm|day|2026-10-04|intake|openai|cost_micros',125000)");
 await c.query("insert into platform_settings(key,value) values('cron:backup:last_success','{\"at\":\"2026-10-04T13:00:00Z\"}')");
 const metrics=await new DbMetricsReader(test.db as unknown as Db,{now:NOW,databaseBytes:async()=>weeklyReport.databaseDecisionBytes+1,storageBytes:async()=>1234}).read();
 expect(metrics.mrrUsd).toBe(tierByKey("starter").annualUsdPerMonth);
 expect(metrics).toMatchObject({topUpsUsd:12.5,cogsUsd:0.1,dailySpendUsd:2.5,llmSpendUsd:0.125,paidPacksMonth:1,payingCustomers:1,r2Bytes:1234});
 expect(metrics.packs).toMatchObject({started:1,done:1,failed:0,needsReview:1,shots:2,medianSeconds:240,longestQueueSeconds:660});
 const text=weeklyMetricLines(metrics).join("\n");
 for(const heading of ["Money","Operations","Triggers"])expect(text).toContain(`\n${heading}\n`);
 expect(text).toContain("First paying customer: REVIEW");
 expect(text).toContain("Queue wait over 10 minutes: REVIEW");
 expect(text).toContain("Database past 300 MB: REVIEW");
 expect(text).not.toContain("demo");
 expect(text).not.toMatch(/backup|restore drill/i);
 expect(metrics).not.toHaveProperty("backupAgeDays");
 expect(metrics).not.toHaveProperty("drillAgeDays");
 expect((await c.query("select key from platform_settings where key='cron:backup:last_success'")).rows).toHaveLength(1);
});
